// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveCandidateTerms(arg1) {
  return window['go']['main']['App']['ApproveCandidateTerms'](arg1);
}

export function GetAllPendingCandidateTerms() {
  return window['go']['main']['App']['GetAllPendingCandidateTerms']();
}

export function GetDomainDictionary() {
  return window['go']['main']['App']['GetDomainDictionary']();
}

export function GetJobCandidateTerms(arg1) {
  return window['go']['main']['App']['GetJobCandidateTerms'](arg1);
}

export function GetJobOutputPath(arg1) {
  return window['go']['main']['App']['GetJobOutputPath'](arg1);
}

export function GetPipelineManifest() {
  return window['go']['main']['App']['GetPipelineManifest']();
}

export function GetRecentCheckpoints() {
  return window['go']['main']['App']['GetRecentCheckpoints']();
}

export function ResumeJob(arg1) {
  return window['go']['main']['App']['ResumeJob'](arg1);
}

export function SaveDomainDictionary(arg1) {
  return window['go']['main']['App']['SaveDomainDictionary'](arg1);
}

export function StopJob(arg1) {
  return window['go']['main']['App']['StopJob'](arg1);
}

export function SubmitJob(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['SubmitJob'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}
