// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApproveASRTranscript(arg1, arg2) {
  return window['go']['main']['App']['ApproveASRTranscript'](arg1, arg2);
}

export function ApproveCandidateTerms(arg1) {
  return window['go']['main']['App']['ApproveCandidateTerms'](arg1);
}

export function ApproveNMTTranscript(arg1, arg2) {
  return window['go']['main']['App']['ApproveNMTTranscript'](arg1, arg2);
}

export function DeleteLogsByFilter(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteLogsByFilter'](arg1, arg2, arg3);
}

export function GetAllPendingCandidateTerms() {
  return window['go']['main']['App']['GetAllPendingCandidateTerms']();
}

export function GetAuditData(arg1, arg2) {
  return window['go']['main']['App']['GetAuditData'](arg1, arg2);
}

export function GetGlobalDictionary() {
  return window['go']['main']['App']['GetGlobalDictionary']();
}

export function GetJobCandidateTerms(arg1) {
  return window['go']['main']['App']['GetJobCandidateTerms'](arg1);
}

export function GetJobManifest(arg1) {
  return window['go']['main']['App']['GetJobManifest'](arg1);
}

export function GetJobOutputPath(arg1) {
  return window['go']['main']['App']['GetJobOutputPath'](arg1);
}

export function GetLogStorageStats() {
  return window['go']['main']['App']['GetLogStorageStats']();
}

export function GetMachineID() {
  return window['go']['main']['App']['GetMachineID']();
}

export function GetMyDictionaryShard() {
  return window['go']['main']['App']['GetMyDictionaryShard']();
}

export function GetPipelineManifest() {
  return window['go']['main']['App']['GetPipelineManifest']();
}

export function GetRecentCheckpoints() {
  return window['go']['main']['App']['GetRecentCheckpoints']();
}

export function GetRecentTelemetryLogs(arg1) {
  return window['go']['main']['App']['GetRecentTelemetryLogs'](arg1);
}

export function GetSetupStatus() {
  return window['go']['main']['App']['GetSetupStatus']();
}

export function GetSyncStatus() {
  return window['go']['main']['App']['GetSyncStatus']();
}

export function OpenJobFolder(arg1) {
  return window['go']['main']['App']['OpenJobFolder'](arg1);
}

export function ResumeJob(arg1) {
  return window['go']['main']['App']['ResumeJob'](arg1);
}

export function RunSetupScript(arg1, arg2) {
  return window['go']['main']['App']['RunSetupScript'](arg1, arg2);
}

export function SaveASRTranscriptProgress(arg1, arg2) {
  return window['go']['main']['App']['SaveASRTranscriptProgress'](arg1, arg2);
}

export function SaveMyDictionaryShard(arg1) {
  return window['go']['main']['App']['SaveMyDictionaryShard'](arg1);
}

export function SaveNMTTranscriptProgress(arg1, arg2) {
  return window['go']['main']['App']['SaveNMTTranscriptProgress'](arg1, arg2);
}

export function StopJob(arg1) {
  return window['go']['main']['App']['StopJob'](arg1);
}

export function SubmitJob(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['SubmitJob'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SyncGlobalRepo() {
  return window['go']['main']['App']['SyncGlobalRepo']();
}

export function SyncLocalShard() {
  return window['go']['main']['App']['SyncLocalShard']();
}

export function TriggerManualSync() {
  return window['go']['main']['App']['TriggerManualSync']();
}

export function UpdateDomainDictionary() {
  return window['go']['main']['App']['UpdateDomainDictionary']();
}
