// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPipelineManifest() {
  return window['go']['main']['App']['GetPipelineManifest']();
}

export function GetRecentCheckpoints() {
  return window['go']['main']['App']['GetRecentCheckpoints']();
}

export function ResumeJob(arg1) {
  return window['go']['main']['App']['ResumeJob'](arg1);
}

export function StopJob(arg1) {
  return window['go']['main']['App']['StopJob'](arg1);
}

export function SubmitJob(arg1) {
  return window['go']['main']['App']['SubmitJob'](arg1);
}
