// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {broker} from '../models';
import {main} from '../models';

export function GetPipelineManifest():Promise<Record<string, broker.PipelineComponent>>;

export function GetRecentCheckpoints():Promise<Array<main.JobSummary>>;

export function ResumeJob(arg1:string):Promise<void>;

export function StopJob(arg1:string):Promise<void>;

export function SubmitJob(arg1:string):Promise<string>;
